// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/iam/authn/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/iam/authn/[...]').default>>>>
    }
    '/api/iam/authn': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/iam/authn/index').default>>>>
    }
    '/api/iam/doodads/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/iam/doodads/[...]').default>>>>
    }
    '/api/iam/doodads': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/iam/doodads/index').default>>>>
    }
    '/api/iam/refresh-tokens/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/iam/refresh-tokens/[...]').default>>>>
    }
    '/api/iam/refresh-tokens': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/iam/refresh-tokens/index').default>>>>
    }
    '/api/iam/users/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/iam/users/[...]').default>>>>
    }
    '/api/iam/users': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/iam/users/index').default>>>>
    }
    '/api/subjects': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/subjects.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/subjects.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/subjects.post').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/subjects.put').default>>>>
    }
    '/api/tasks': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks.post').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks.put').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}